version: '3'
services:
  ts-code-server:
    image: tailscale/tailscale:latest
    hostname: code-server
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/code-server.json
    volumes:
      - tailscale-data-code-server:/var/lib/tailscale
      - ${PWD}/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    ports:
      - "8080:8080"
    restart: unless-stopped

  code-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_URL=${MONGO_URL}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - RECEIVER_EMAIL=${RECEIVER_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    volumes:
      - ./src:/home/coder/project/src
      - ./research:/home/coder/project/research
    network_mode: service:ts-code-server
    depends_on:
      - ts-code-server
    command: ["--auth", "none", "/home/coder/project"]
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

volumes:
  tailscale-data-code-server:
    driver: local