version: '3'
services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_URL=${MONGO_URL}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - RECEIVER_EMAIL=${RECEIVER_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./src:/home/coder/project/src
      - ./research:/home/coder/project/research
    command: ["--auth", "none", "/home/coder/project"]

  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped