version: '3'
services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile  # Specify your Dockerfile name if it's different
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "8080:8080"
    volumes:
      - ~/.ssh:/home/coder/.ssh
      - ./src:/home/coder/project/src
    command: ["--auth", "none", "/home/coder/project"]

  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped